### ISSUE TITLE
exsearch配合pjax的修改

### ISSUE THREAD

**Issue by inokoe** [youranreus/G#11]
exsearch 插件默认使用data-url中的地址，看到源码发现是这个函数
    function T(n) {
        //n && n.length && (location.href = n.attr("data-url"))
    }
location.href 打破了pjax，导致直接页面刷新。为了音乐不被打断，得改下。
所以先注释掉这句话

原版这个亚子
//return i("<div>").addClass("ins-selectable").addClass("ins-search-item").append(i("<div>").addClass("header").append(i("<i>").addClass("iconfont").addClass("icon-" + n)).append(null != e && "" != e ? e: c.TRANSLATION.UNTITLED).append(t ? i("<span>").addClass("ins-slug").text(t) : null)).append(a ? i("<p>").addClass("ins-search-preview").html(a) : null).attr("data-url", r)

进行添加<a>标签和onclick函数

return i("<a>").attr("href", r).attr("onclick","exsearchpoint()").append(i("<div>").addClass("ins-selectable").addClass("ins-search-item").append(i("<div>").addClass("header").append(i("<i>").addClass("iconfont").addClass("icon-" + n)).append(null != e && "" != e ? e: c.TRANSLATION.UNTITLED).append(t ? i("<span>").addClass("ins-slug").text(t) : null)).append(a ? i("<p>").addClass("ins-search-preview").html(a) : null).attr("data-url", r))

自动关闭搜索框：
1.给搜索框关闭<i>标签加个ID ，我是 "exsearch-close-point"
2. x.js里随便一丢
 	function exsearchpoint(){
$("#exsearch-close-point").click();
  }

业余编程，写的不对请提出

**Comment by youranreus** [comment]
挖一下坟hhhh，首先感谢你的给出的代码建议~
之前尝试了你的代码之后有一些小问题，后来因为各种原因一直没有管这个问题
这两天有人说才发现exsearch插件已经支持自定义回调函数了，最近才完善这个点🤣
