### ISSUE TITLE
DPlayer插件与G主题不适配

### ISSUE THREAD

**Issue by xhlove** [youranreus/G#13]
https://github.com/MoePlayer/DPlayer-Typecho
使用G主题后，DPlayer点击进度条会从头播放，而且视频的外框（？）比例均不正常。
使用默认主题没有这个问题。
示例：https://blog.weimo.info/archives/443/
默认
![G](http://puui.qpic.cn/vshpic/0/IbdnP5fynWmkkc2Fr6cFfXF44RBmv9Edm1AcJb2QA886tNJ6_0/0)
![默认](http://puui.qpic.cn/vshpic/0/sBKac7RiP4djUUhZDkeFeWIz4_6_AMye2ocpyyR6nCVUtOjM_0/0)

**Comment by youranreus** [comment]
新版本集成了Dplayer，样式问题也已经修复

**Comment by xhlove** [comment]
感觉大佬，这两天就升级下主题！

**Comment by xhlove** [comment]
拖了很久终于升级了主题，现有问题如下：
1. 同一个文章不能插入两个视频，插入两个视频时只会加载最后一个。
2. 使用m3u8链接（mp4链接没问题）作为播放来源时提示`Uncaught ReferenceError: Hls is not defined`，使用的代码：
```
[dplayer url="https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBGaeCQMAFdcDdg.m3u8" pic="" /]
```
而且诡异（？）的是这个报错一开始是：
```javascript
DPlayer.min.js:sourcemap:1 Uncaught ReferenceError: Hls is not defined
    at e.value (DPlayer.min.js:sourcemap:1)
    at e.value (DPlayer.min.js:sourcemap:1)
    at new e (DPlayer.min.js:sourcemap:1)
    at <anonymous>:2:19
    at t.activateScript (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at t.run (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at HTMLScriptElement.<anonymous> (rocket-loader.min.js:1)
```
然后变成
```javascript
player.js:358 Uncaught ReferenceError: Hls is not defined
    at e.value (player.js:358)
    at e.value (player.js:453)
    at new e (player.js:175)
    at <anonymous>:2:19
    at t.activateScript (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at t.run (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at HTMLScriptElement.<anonymous> (rocket-loader.min.js:1)
```

**Comment by xhlove** [comment]
其他新发现，原生typecho的Dplayer的插件有开启hls和flv支持的选项，开启这个可以播放m3u8文件。
另外安卓版chrome上不用开这个也能播放，貌似是因为手机上Chrome原生支持m3u8的原因吧？
还有就是在手机上Chrome请求m3u8和具体文件的时候，不会带referer，PC端始终会带，然后跨域就无法访问了。

**Comment by xhlove** [comment]
update
在老版EDGE中，如果插入的m3u8是允许跨域访问的，那么edge可以播放，不需要hls.min.js，而在Chrome中会提示HLS is not defined。
同时把Dplayer插件开启（并开启hls支持），虽然会加载两次，但是chrome也可以正常播放了。
所以我可以：
1. 修改主题代码，加载hls.min.js以支持m3u8的加载。
2. 使用G主题并同时开启Dplayer插件+HLS支持。

另外使用支持跨域的m3u8。
