### ISSUE TITLE
“关于”页插入图片的bug

### ISSUE THREAD

**Issue by yesmiley** [youranreus/G#14]
插入的图片，会按照图片本身的尺寸进行显示，不会有缩放处理，导致图片右边宽度超出界面，完全没法看……

**Comment by youranreus** [comment]
抱歉，这是我的疏忽，新版本已修复

**Comment by yesmiley** [comment]
多谢！大佬辛苦（滑稽）

然后这里还遇到了几个小问题，不耽误你的话，帮我看看吧

**第一个是友链页面进行引用的问题，文章也有这个问题**
语法应该没有错（之前用其它主题，显示正常）
![image](https://user-images.githubusercontent.com/32222791/76066447-98361300-5fc8-11ea-937c-564c7b9e3931.png)
但是解析出来，顶格了（眼睛疼）
![image](https://user-images.githubusercontent.com/32222791/76066523-c156a380-5fc8-11ea-8e77-e6287a4ad236.png)
如果我这样写
![image](https://user-images.githubusercontent.com/32222791/76066569-d59aa080-5fc8-11ea-9d91-0a06178131d2.png)
解析出来，第二行就是正常的（好诡异）
![image](https://user-images.githubusercontent.com/32222791/76066632-eea35180-5fc8-11ea-90c7-fe771ca7cdd0.png)

**第二个就是返回顶部的按钮**
我在手机上是会显示的，电脑上就不显示……

**Comment by yesmiley** [comment]
抱歉，再反馈一个类似的显示产出界面bug

当在 序号 语法中（1.这种）插入链接，链接会无视超界，向右延伸，直到链接显示完全

理论上这个应该是要换行显示才对

**Comment by youranreus** [comment]
第一个我试了一下好像没有问题，第二个链接的问题修复了。两个课间没了（汗）

**Comment by yesmiley** [comment]
😂 抱歉！大佬辛苦了，先不耽误你学习了，我自己捣鼓捣鼓

**Comment by yesmiley** [comment]
可以问下大佬的配置情况吗
今天换了台机器（更新的PHP和nginx），引用缩进还是有问题。
开始怀疑是typecho版本问题了，我用的是1.2 (18.10.23)

**Comment by youranreus** [comment]
我的typecho版本为1.1 (17.10.30)
配置的话，用的虚拟主机，PHP版本为7.2

**Comment by yesmiley** [comment]
好的谢谢
