### ISSUE TITLE
评论时若填写用户名与已存在用户名相同，则评论提交失败，且未提示游客出错原因

### ISSUE THREAD

**Issue by zhengzubing** [youranreus/G#15]

**Comment by yuansky88** [comment]
这个是数据库的原因，评论的时候，相通数据不能同时存在，当登录账号时，这个问题将会解决，现在暂时的解决办法就是：开放注册，才能评论，好像连原有的主题都有这个情况

**Comment by yuansky88** [comment]
我细细的研究了一番，发现之前的答案有问题，所以修改了，确保解决问题到位

**Comment by youranreus** [comment]
新版本已经能够提示出错原因
