### ISSUE TITLE
[BUG] 关于换页过渡动画

### ISSUE THREAD

**Issue by yesmiley** [youranreus/G#18]
在某些情况下（貌似是网络状况不太好的时候），从当前页点击目标页面切过去的时候，过渡动画播放完成会闪会当前页，过一会再展示目标页。不知道大佬是否注意到了这个问题？
目前暂时的解决办法似乎是把过渡动画的时长调大一点，不过数值太大了也会影响体验，并且有时候调大了还是会这样。

**Comment by youranreus** [comment]
这个我也十分苦恼，暂时没找到除了调长时间的解决方案QAQ

**Comment by yesmiley** [comment]
好吧，那先这样。
