### ISSUE TITLE
代码块没有自动换行

### ISSUE THREAD

**Issue by AHpxChina** [youranreus/G#24]
如果某个语句过长并且没有换行符的话，它会一直延伸而不是到达边缘自动换行

**Comment by yuansky88** [comment]
你可以使用一个插件，叫代码高亮，然后删除主题自带的代码高亮，好像是一个prism.js还有css文件，删除后，根据插件的文档提示一步一步的做就行了，如果显示错误，检查你的G.css是否添加需要的样式表，对于pjax，可以看看我博客里的方法：www.yzdblog.cn ，然后代码会忠实的表现出来，如果延伸，也自带滚动条，样式也好看，我擅长于这款主题的魔改😀

**Comment by yuansky88** [comment]
代码高亮的名称叫Code Prettify，直接使用会与原主题冲突

**Comment by AHpxChina** [comment]
> 你可以使用一个插件，叫代码高亮，然后删除主题自带的代码高亮，好像是一个prism.js还有css文件，删除后，根据插件的文档提示一步一步的做就行了，如果显示错误，检查你的G.css是否添加需要的样式表，对于pjax，可以看看我博客里的方法：www.yzdblog.cn ，然后代码会忠实的表现出来，如果延伸，也自带滚动条，样式也好看，我擅长于这款主题的魔改😀

谢谢老哥，问题解决了
