### ISSUE TITLE
[BUG] 长链接无法换行显示，导致网页往右横扩

### ISSUE THREAD

**Issue by if1y** [youranreus/G#25]
### ⚠️ 可能描述不够清晰，建议直接发一篇链接够长的博文，分别用电脑、手机测试自行感受。

---
### 问题描述
其实这个问题之前 https://github.com/youranreus/G/issues/14#issuecomment-595862605 提过，当时“修复”也没仔细验证。现在看了下还是没能解决。
为避免自己用的不是最新版本，用作者自己的站、测试并截图：
![image](https://user-images.githubusercontent.com/32222791/108723908-b7bea680-755f-11eb-8f38-6446a02ee802.png)

可以发现：
**当文字加上外链时，无法换行显示。**
**如果链接够长，用户窗口又够短（即用户窗口小于链接长度）时，链接就会往右侧超出。**

### 带来的问题
- 影响页面美观 _（这还是其次）_
- 链接内容展示不全 _（有可能超出屏幕外而无法显示完全）_
- 窗口横向扩大，导致滑屏时体验极差，很容易滑到右侧的拓展区域

### 影响范围
- **主要是手机端**
- 对于 PC端/Pad端 几乎无影响，因为网页链接通常不会过长，所以无法体现出问题，但**在链接确实足够足够长的时候，还是能够复现**（如下图）
![image](https://user-images.githubusercontent.com/32222791/108726265-2b61b300-7562-11eb-998c-c5abaca8e640.png)

**Comment by youranreus** [comment]
我直接哭泣，之前某个版本是修复了，不过好像又被我后来的代码覆盖掉了。
是我犯病了😥

**Comment by youranreus** [comment]
已修复（真的修复了）

**Comment by if1y** [comment]
### 说个鬼故事：这个问题还在…… 😂

- 自己更到最新，复现

- 避免因自行魔改导致，测试了你的博客，复现
   ![image](https://user-images.githubusercontent.com/32222791/113284967-f729a100-931c-11eb-9744-c8fe2c2508b4.png)

- 杏铃の小本的博客亦能复现
   ![image](https://user-images.githubusercontent.com/32222791/113285158-33f59800-931d-11eb-86f9-ac7dbb6a2303.png)
