### ISSUE TITLE
Pjax导致的“炫彩鼠标”插件的部分功能失效

### ISSUE THREAD

**Issue by yuansky88** [youranreus/G#26]
因为启用了pjax，插件“炫彩鼠标”。在点击网站内的a标签元素后，在新的界面中a标签的鼠标显示变成了默认，可能是因为在pjax容器内无感刷新后，导致的炫彩鼠标的js文件不执行！（只是可能情况），在最新版本中，这个问题仍然存在！希望解决！
网站:[https://www.lhyblog.cn](url)
使用的版本:G v1.6

**Comment by youranreus** [comment]
你好，你的网站现在无法打开了QWQ，所以无法准确判断。
不过根据你的描述应该和你说的原因差不多。这种情况下你可能需要去找一下插件的文档看看有没有重载函数什么的，可以添加到`JS/X.js`文件中的`pjax_complete()`函数进行重载。
