### ISSUE TITLE
预览图无法加载

### ISSUE THREAD

**Issue by SKT250** [youranreus/G#31]
图片一直转圈圈，点进去就正常，W主题没这问题
![图片](https://user-images.githubusercontent.com/68404788/115708440-941ead80-a3a2-11eb-9e55-0a834b28e332.png)

**Comment by SKT250** [comment]
> 
> 
> 图片一直转圈圈，点进去就正常，W主题没这问题
> ![图片](https://user-images.githubusercontent.com/68404788/115708440-941ead80-a3a2-11eb-9e55-0a834b28e332.png)

**Comment by SKT250** [comment]
**_大户大户时间 _**

> 
> 
> 图片一直转圈圈，点进去就正常，W主题没这问题
> ![图片](https://user-images.githubusercontent.com/68404788/115708440-941ead80-a3a2-11eb-9e55-0a834b28e332.png)

**Comment by youranreus** [comment]
看看是不是jquery冲突了，话说你这个是网卡了吗。

**Comment by SKT250** [comment]
也许是搜索插件的问题

**Comment by SKT250** [comment]
@youranreus 解决了，把ExSearch的引入 JQuery关掉就行了
