### ISSUE TITLE
小视频显示问题

### ISSUE THREAD

**Issue by ZiXia1** [youranreus/G#34]
同作者小视频，为什么我的有问题
重新下了遍主题，和清除缓存都一样
https://img14.360buyimg.com/ddimg/jfs/t1/172822/13/9787/18773/609e7852E5baeee3a/fddcc6991dcc9c63.png
https://img11.360buyimg.com/ddimg/jfs/t1/195544/8/3068/4552/609e7851E6b39e443/5c243bfe78bbb89f.png

**Comment by youranreus** [comment]
你能发一下你的站吗，我看一下

**Comment by ZiXia1** [comment]
blog.cdnmc.c

> 你能发一下你的站吗，我看一下

blog.cdnmc.cn

**Comment by ZiXia1** [comment]
> 你能发一下你的站吗，我看一下

blog.cdnmc.cn

**Comment by youranreus** [comment]
你是不是改了什么地方，你这样子引入js的话浏览器就不会解析原本的一些代码了
建议你要加js文件的话单独写一个script
![sshot-7](https://user-images.githubusercontent.com/24204866/118285510-19116880-b504-11eb-8548-6789b3069389.png)

**Comment by ZiXia1** [comment]
解决了，当初图方便，直接后台加
