### ISSUE TITLE
移动设备下，底栏图标变为隐藏

### ISSUE THREAD

**Issue by if1y** [youranreus/G#35]
准确说是窗口宽度较小时，底栏的又拍云和阿里云图标 `div id=footer-content-right` 就消失了。

我记得以前是不会隐藏的，并且感觉隐藏不是个好主意……

**Comment by youranreus** [comment]
emmm，我看看整一个开关出来吧。之前是出于美观考虑才隐藏了

**Comment by hshx123** [comment]
确实，有点担心又拍某天拿手机页面审核(

**Comment by youranreus** [comment]
2.5.1版本可以开关是否在移动端显示了
