### ISSUE TITLE
<details></details>标签之折叠图片加载bug

### ISSUE THREAD

**Issue by xhlove** [youranreus/G#38]
个人感觉这个可能不是G主题的bug，但是希望作者大大能看一眼

我尝试使用`<details>`标签尝试把图片折叠（这么做纯粹是想加一个文章头图，但是同时希望如果有人想点开图片看看也能正常看），参考代码如下

```
<details>
<summary>img</summary>
![一张无意义文章头图](https://blog.weimo.info/usr/uploads/2021/09/1995710565.png)
</details>
```

然后一开始会自动加载转圈图标

https://cdn.jsdelivr.net/gh/youranreus/R@v1.1.5/G/IMG/loading2.gif

不过这个时候如果**鼠标不移动**，那么实际上不会加载（显示）图片（实际上已经请求过服务器了）

只有滚动鼠标才会加载图片，问题之一

另外可以注意到图片**再次被加载了两次**，问题之二

![oCam_2021_09_11_12_32_21_306](https://user-images.githubusercontent.com/48152166/132936403-a5d63f91-8e5a-438e-bcb3-16c2bd76b5f6.gif)

查看网络请求可以看到图片已经请求了两次，一次是正文部分的一次是标题背景

最理想的情况应该是只加载一次并且展开折叠标签的时候直接显示，而不是再次加载

或者能展开时直接显示也足够了，不过流量不值钱再次请求两次也可以接受

但是点开后就主动请求/加载/显示希望能修复，不然总感觉网络坏了

**Comment by youranreus** [comment]
我尝试修复一下

**Comment by youranreus** [comment]
在没修复好之前可以尝试用主题的折叠框段代码代替一下

**Comment by xhlove** [comment]
感谢

**Comment by xhlove** [comment]
是Disable Cache引起的，实在抱歉。
