### ISSUE TITLE
在主题外观设置关于相对链接的问题

### ISSUE THREAD

**Issue by qinians** [youranreus/G#47]
## 声明：本Issue并不是什么致命bug，但是会造成使用不便。
在主题外观设置中，其链接无法使用相对链接

#### 头部背景图：
使用 https://www.qinians.com/resources/images/headbackground.jpeg 则可以正常显示图片
而用 ./resources/images/headbackground.jpeg 相对路径无法显示

## Result
这会带来一个不便，就是网站更换域名后，需要把所有链接中的域名更换

**Comment by youranreus** [comment]
相对链接。。
你试试`./resources/images/headbackground.jpeg`和`/resources/images/headbackground.jpeg`有什么区别

**Comment by qinians** [comment]
好吧...就是这个主题外观设置链接，对使用图床的还是方便的。
因为图床慢而使用本地服务器文件的比较麻烦，希望可以直接引用本地文件

**Comment by youranreus** [comment]
我刚刚的第二种方式不能用吗？感觉没必要特意加个引用本地文件的功能，理解url了之后很轻松就能引用吧

**Comment by qinians** [comment]
第二种还是用不了。

**Comment by youranreus** [comment]
我在你的网站试了一下，是可以的
