### ISSUE TITLE
强迫症的问题

### ISSUE THREAD

**Issue by xhlove** [youranreus/G#5]
**搜索放在头部后效果不统一**
模板的搜索默认是在下方的，但在页面较长的时候，比如文章界面，如果想搜索的话就不太方便，于是我想把它放在顶部，也就是和“首页 文章 友人帐 关于”并列，于是我在header.php这部分代码紧接着粘贴了底部“搜索”部分的代码，即
```php
<?php if (isset($this->options->plugins['activated']['ExSearch'])) : ?>
<a class="search-form-input">搜索</a>
<?php endif ?>
```
不过修改后，当鼠标放在顶部的搜索处时，它和鼠标放在“首页 文章 友人帐 关于”的样子不一样，前者是一个“I”，后者是一个手，见下图：
![不统一.png](https://i.loli.net/2019/08/13/BC6FQIdN1mnkKt9.png)
![统一.png](https://i.loli.net/2019/08/13/PiF7MLDAk52jydU.png)
于是强迫症病发，后来有个大佬这么回复我：a没有href属性被回落了，加个空js或者#上去就行，或者就是丢失css属性了。
于是给它添加了一个href属性，然后就达到统一的效果了，代码如下：
```php
<?php if (isset($this->options->plugins['activated']['ExSearch'])) : ?>
<a href="#" class="search-form-input">搜索</a>
<?php endif ?>
```
![强迫症需要的结果.png](https://i.loli.net/2019/08/13/BRhCmbzj9tMHNLg.png)
**返回顶部按钮无效**
在PC和安卓的Chrome均没有反应。
**代码高亮**
在网络不好的时候，代码一行过长的话，如果恰好js没有加载完，那么较长的代码就会溢出页面，这个可能属于高亮插件的问题？
**网络慢引出的其他问题**
网络特别差，比如主机在国外同时又在网络高峰期时，页面大致加载出来了，但有些js一直加载不出来，这个时候在安卓Chrome或者其他移动端浏览器表现出页面无法滑动的现象，非常影响浏览体验，不知道这个情况除了将一些js改成第三方的地址加以改善外，有没有其他手段可以优化一下？
虽然是些无伤大雅的小问题，不过可以的话还请看看，谢谢！

**Comment by xhlove** [comment]
追加一个关于JS的问题，目前在console里面可以看到
```JavaScript
Uncaught ReferenceError: InstantClick is not defined
    at X.js:1
```
然后依葫芦画瓢在footer.php里面加了instantclick.min.js
```JavaScript
<script src="https://cdn.jsdelivr.net/npm/instantclick@3.1.0-2/dist/instantclick.min.js"></script>
```
然后还是有错误，如下：
```JavaScript
X.js:1 Uncaught ReferenceError: _hmt is not defined
    at X.js:1
    at Object.on (instantclick.min.js:1)
    at X.js:1
```
我使用了cdn，不知道是不是和cdn有关系？
这个报错好像对浏览没有影响，不过怪不舒服的...

**Comment by youranreus** [comment]
感谢反馈！这周末尽量抽时间看看。不过更新可能会有点慢QAQ

**Comment by xhlove** [comment]
从nginx错误日志发现一个问题，提示是
`2019/09/04 08:05:36 [error] 3312#0: *5952 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: imgurl in /path/to/var/Typecho/Config.php on line 173" while reading response header from upstream, client: 172.68.141.244, server: xxx, request: "GET /archives/401/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "xxx", referrer: "xxx"`
`/var/Typecho/Config.php`这个路径是typecho的路径
imgurl 这个好像只在你的模板中出现过一次，不知道这个错误是什么，但看起来不影响使用。
