### ISSUE TITLE
侧边栏点击失效，文章页面标题css异常

### ISSUE THREAD

**Issue by SXBW** [youranreus/G#52]
评论提示<br>
pc端QQ浏览器侧边栏点击失效，文章页面标题css异常

**Comment by SXBW** [comment]
![image](https://user-images.githubusercontent.com/58621224/147111596-2373ccae-0816-40c6-93ef-6e08af549b03.png)

**Comment by LiCaoZ** [comment]
console 看看有没有报错

and 你这个字体硬生生把页面加载时间拖到了极其恐怖的三分多钟，G 主题由于一些特性使得 js 在页面完全加载后生效，所以在你字体加载完之后按钮是不会生效的XD
![image](https://user-images.githubusercontent.com/67832651/147122655-0f884545-f12d-4934-b713-d0b22edc6555.png)
~~建议停止使用过时 chromium内核 浏览器解千愁~~

**Comment by SXBW** [comment]
没加字体也这样

**Comment by youranreus** [comment]
请规范title

**Comment by youranreus** [comment]
https://github.com/youranreus/G/commit/7ececd280a6bd7dc308cc8d6b8d82b7fd24edec5
这里应该稍微修复了一下加载主题JS文件的问题，可以clone一下试试

**Comment by youranreus** [comment]
标题CSS问题，请在插入视频的短代码前多打几个空行试试

**Comment by youranreus** [comment]
fixed in https://github.com/youranreus/G/commit/74375074fb995b5eb638167c6eddbecd108e440d

**Comment by SXBW** [comment]
膜拜大佬
