### ISSUE TITLE
有时dplayer视频需要刷新网页才能显示

### ISSUE THREAD

**Issue by qinians** [youranreus/G#57]
有时dplayer视频需要刷新网页才能显示

**Comment by LiCaoZ** [comment]
有测试链接吗，或者 console 的报错信息

**Comment by qinians** [comment]
https://www.qinians.com/archives/videos.html

**Comment by LiCaoZ** [comment]
嘶 重庆移动/电信都正常啊🤔

涉及到我的知识盲区了属于是

**Comment by qinians** [comment]
dplayer是偶现的，使用cplayer这个很明显
demo：https://www.qinians.com/songs-list.html

**Comment by qinians** [comment]
噢对，直接点击链接是可以直接加载的，如果是站内点击进去的话会出现这个问题，貌似是pjax把

**Comment by qinians** [comment]
https://www.qinians.com/
从初始页面在站内点到那页面（https://www.qinians.com/archives/videos.html）大概率发生这个问题

**Comment by LiCaoZ** [comment]
Uncaught SyntaxError: Identifier 'dplayer1' has already been declared
    at module.exports (pjax.min.js?v=3.10012:1)
    at pjax.min.js?v=3.10012:1
    at NodeList.forEach (<anonymous>)
    at module.exports (pjax.min.js?v=3.10012:1)
    at module.exports (pjax.min.js?v=3.10012:1)
    at pjax.min.js?v=3.10012:1
    at NodeList.forEach (<anonymous>)
    at module.exports (pjax.min.js?v=3.10012:1)
    at pjax.min.js?v=3.10012:1
    at Array.forEach (<anonymous>)

就是 pjax 的问题惹，火速召唤@youranreus

**Comment by youranreus** [comment]
哈！我根本没有写dplayer的重载函数

**Comment by youranreus** [comment]
fixed in https://github.com/youranreus/G/commit/f9fb6f83ffdc7b36e0326b303339dbcacc6a3501
