### ISSUE TITLE
短代码photos 添加图片过多似乎会出现bug

### ISSUE THREAD

**Issue by coolarec** [youranreus/G#59]
![image](https://user-images.githubusercontent.com/46271219/150720853-a9554dd6-a275-40e5-b6f2-c4ef19392fb6.png)
检查过了应该不是我写错了（上面的都能正常显示）

**Comment by youranreus** [comment]
可以贴一下编辑器的源文档吗

**Comment by coolarec** [comment]
大佬回复了，我换了个别的主题也是这个毛病，最后发现是自己换行不规范。打扰了打扰了。
