### ISSUE TITLE
在部分浏览器中文章标题显示错位

### ISSUE THREAD

**Issue by i-loli** [youranreus/G#61]
我在Chrome 83.0.4103.106版本中会出现以下问题，最新版的正常显示。

当文章添加文章头图时，标题会如图错位显示。如果不设置则会正常显示。
![IMG_20220201_033949](https://user-images.githubusercontent.com/42514208/151862106-4c933367-dcaa-45d2-947d-99b0bd6dbed7.jpg)

并且右下角的三个按钮似乎在手机端就没有用。并且侧边栏在一些内核比较落后的浏览器中无法显示。而这些落后的浏览器反而会经常使用到。

**Comment by youranreus** [comment]
是这样子的，在dev分支已经修复，但是不知道为什么作者没有发布新版本，我这就去催一催

**Comment by youranreus** [comment]
已经发布新版本了

**Comment by i-loli** [comment]
好的！谢谢！
