### ISSUE TITLE
建议把原来的友链界面改回来

### ISSUE THREAD

**Issue by lizhijunya** [youranreus/G#66]
其实我感觉悠然把友链改成这样子是个错误的选择，只单纯显示一个头像，博主的个人简介就没了意义，而且只有把鼠标放在头像上面才会显示博客名称，对手机用户极其不友好，希望悠然能在下个release改回去（第一次提pr

**Comment by LiCaoZ** [comment]
你要提嘛，你提的话我就不管啦🤔

**Comment by youranreus** [comment]
fixed in https://github.com/youranreus/G/commit/caf11bd4fa0d0188398121e953248196a8272eb7

**Comment by lizhijunya** [comment]
感谢悠然~

**Comment by lizhijunya** [comment]
悠然，这个玩意我发现就是说css会错乱，确定效果xiaolii.com/links.html

**Comment by youranreus** [comment]
dev分支的话只能使用本地源，不能用ahdark或者jsdelivr哈

**Comment by LiCaoZ** [comment]
可以把需要的 CSS 添加到自定 CSS 里~

**Comment by lizhijunya** [comment]
> dev分支的话只能使用本地源，不能用ahdark或者jsdelivr哈

搞定了！谢谢悠然！
