### ISSUE TITLE
图片预览的相关功能建议

### ISSUE THREAD

**Issue by jstar0** [youranreus/G#77]
记得在2.x版本时，博文内点击图片后，会进入灯箱并提供操作按钮，有放大、缩小等多种功能。这些功能非常便利，对移动小屏用户的帮助尤其明显。

期望能重新添加图片预览的相关功能，谢谢！

**Comment by youranreus** [comment]
收到，预计7月份会添加（目前正在复习周qaq

**Comment by jstar0** [comment]
悠然加油！🥰💯

**Comment by youranreus** [comment]
3.3.4版本已经添加~
