### ISSUE TITLE
移动设备浏览器搜索界面显示空白

### ISSUE THREAD

**Issue by jstar0** [youranreus/G#82]
用手机浏览器打开搜索框，是空白一片（电脑端没问题）
主题版本是G-3.3.4，ExSearch也是用的悠然的修复版

问题每次都复现：www.mcxin.top
尝试重建索引：如果用手机重建索引，同一设备会暂时恢复正常（用无痕模式打开依然不行）；用电脑重建索引，移动设备依然空白一片

**Comment by youranreus** [comment]
看了一下，是请求exsearch的api时出了问题，可以把插件的静态化选项打开试试
