### ISSUE TITLE
在PHP8.1下，点赞按钮“出了点小问题”

### ISSUE THREAD

**Issue by jstar0** [youranreus/G#88]
G主题为3.3.6版本，Typecho1.2.0，PHP8.1，点击点赞按钮会提示“出了点小问题”
切换到PHP7.4后就没有问题了，是Ajax的事吗
（能否适配一下高版本PHP :D）

**Comment by youranreus** [comment]
这两天会排查一下

**Comment by jstar0** [comment]
辛苦您了🥰Best Regards,  景星 | JStar
