### ISSUE TITLE
控制台警告

### ISSUE THREAD

**Issue by BambooMC** [youranreus/G#89]
`The resource http://h**estu.****omc.cn/usr/themes/G-3.3.6/static/js/spotlight.bundle.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

Element not found: tocbot.min.js?v=3.211:1 
s.destroy @ tocbot.min.js?v=3.211:1
（匿名） @ G.min.js?v=3.3.6:1
（匿名） @ pjax.min.js?v=3.10012:1
module.exports @ pjax.min.js?v=3.10012:1
（匿名） @ pjax.min.js?v=3.10012:1
module.exports @ pjax.min.js?v=3.10012:1
loadUrl @ pjax.min.js?v=3.10012:1
linkAction @ pjax.min.js?v=3.10012:1
（匿名） @ pjax.min.js?v=3.10012:1
/archives/start.html:1 The resource http://h**estu.******omc.cn/usr/themes/G-3.3.6/static/js/spotlight.bundle.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

**Comment by youranreus** [comment]
3.3.7版本应该修复了这个问题

**Comment by BambooMC** [comment]
已解决，谢回复
