### ISSUE TITLE
配置文档无法访问

### ISSUE THREAD

**Issue by cnKyana** [youranreus/G#90]
由于Vercel被DNS污染，部署在vercel.app域名上的文档无法访问。已经尝试绕过，直接访问GitHub Pages的默认链接，但失败。希望悠然可以更新一下文档链接

**Comment by cnKyana** [comment]
暂时的一个解决：克隆[youranreus/G.github.io](https://github.com/youranreus/G.github.io)到本地，使用VSCode插件Live Server或者其它方式在本地打开一个服务器，访问index.html，即可打开文档。

**Comment by youranreus** [comment]
文档已经迁移了，现在试试看qwq

**Comment by cnKyana** [comment]
已经可以访问了，谢谢。
