### ISSUE TITLE
一些建议和bug反馈

### ISSUE THREAD

**Issue by XiaoPampo** [youranreus/G#93]
bug
1.在3.3.7版本中归档页独立页面会出现无法加载，刷新后会出现下方的dock栏宽度错误
2.浏览文章刷新的时候浏览次数会以3个3个的增加，我目前是使用的是3.3.4版本。3.3.7貌似也有，在部分浏览器会出现这样的情况，有点是1个1个的增加，已经排除插件问题，确定是主题问题，视频私发了
3.在您的网站 G主题小组件配置 https://g-editor.imouto.tech/ 中生成的json配置中类型name是错误的，应该是type（害得我搞了好久:(

suggestion
1.让单列样式的文章列表卡片宽度能够一致，有的文章字数不一样导致卡片的宽度不一样（强迫症难受死了）
2.loading.gif加载动画的优化，我这里提供一个https://pampo.cn/usr/themes/G/static/img/loading2.gif
3.黑色主题能够设置是否自动黑色（永日白天？），当然还是希望能有个跟随系统（别人能做的我们悠然宝贝也能做到❤😍）
4.备份主题数据后能够在主题设置显示 已/未备份主题
5. 。。。

**Comment by youranreus** [comment]
目前在php7.2和php8.0环境下测试都不能复现前两个问题，你可以换上3.3.7看一下不，我去排查一下

**Comment by youranreus** [comment]
黑色主题能够设置是否自动黑色是可以手动设置的，在
![image](https://user-images.githubusercontent.com/24204866/216750023-d31d8028-153e-4bf8-ba58-a02d95a62627.png)
不过这里我也会添加上跟随系统

**Comment by XiaoPampo** [comment]
emmm,dock栏那个bug不知道为什么我也恢复不过来了，浏览次数 那个问题我这各个版本都试过了，也还有这个问题，不过这个问题只是在部分浏览器上出现，我目前是在ios上的edge浏览器上出现，其它都没什么问题

**Comment by youranreus** [comment]
我在Mac/window的edge/chrome，安卓的edge/chrome上测试都没有问题。你可能要看一下是不是浏览器的cookie设置问题哈。

**Comment by youranreus** [comment]
3.3.8版本已经修复并且增加了以下功能
- 小组件配置修复（非常感谢指出这个问题
- loading动画gif更换
- 夜间模式跟随系统
- 主题备份功能优化

**Comment by youranreus** [comment]
“让单列样式的文章列表卡片宽度能够一致”
这个问题没有理解到，可以详细描述一下吗

**Comment by XiaoPampo** [comment]
备份主题设置貌似有点问题,点击备份会显示备份失败，但是实际上是有备份的,也能正常恢复，
黑色主题的控制逻辑是 时间段和跟随系统  两个一起控制吗？我还不太清楚，我目前测试是两个一起控制，能否增加一个  黑色主题是  跟随系统or时间段or两个都关闭
浏览次数应该是我的问题，ios端edge浏览器会有这问题

**Comment by youranreus** [comment]
right here 👇🏻
https://github.com/youranreus/G/releases/tag/v3.3.9
