### ISSUE TITLE
发现一个小BUG，文章双栏模式不对齐

### ISSUE THREAD

**Issue by Vicoeo** [youranreus/G#96]
![QQ截图20230217101008](https://user-images.githubusercontent.com/95205433/219532083-770dec3d-42ac-4c36-a455-44c508043cba.png)
看这个截图可以看出文章页面只能显示5个，第6个没有显示，导致文章页面右下角会空出来，请问怎么解决啊

**Comment by youranreus** [comment]
<img width="1022" alt="截屏2023-02-18 21 18 38" src="https://user-images.githubusercontent.com/24204866/219868130-b09acc45-503d-4a93-8cf4-bf661f51dde4.png">
在这里设置噢
